import crypto from "crypto";
import PDFDocument from "pdfkit";

// ─── Built-in e-sign system ───────────────────────────────────────────────────
// No third-party provider. Tokens are generated locally; clients sign via the
// partner portal's /esign/:token page. Signed PDFs are a certificate of completion
// stored back into the documents table.

export interface EsignSigner {
  id: string;
  name: string;
  email: string;
  role?: string;
  signingOrder: number;
}

export interface CreateEnvelopeParams {
  documentName: string;
  fileBase64: string;
  fileName: string;
  signers: EsignSigner[];
  subject?: string;
  message?: string;
}

export interface EnvelopeResult {
  providerEnvelopeId: string; // kept for DB compat — same as review_token
  reviewToken: string;
  status: string;
}

export function generateReviewToken(): string {
  return crypto.randomBytes(32).toString("hex");
}

export function isSignwellConfigured(): boolean {
  return true; // built-in — always available
}

// ─── Certificate of Completion PDF ───────────────────────────────────────────

export interface SignatureCertParams {
  documentName: string;
  signerName: string;
  signerTitle?: string | null;
  signatureImage: string; // base64 PNG data URL
  signedAt: Date;
  envelopeId: number;
}

function bufferDoc(doc: InstanceType<typeof PDFDocument>): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    doc.on("data", (c: Buffer) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);
    doc.end();
  });
}

export async function generateSignatureCertificate(params: SignatureCertParams): Promise<Buffer> {
  const doc = new PDFDocument({ size: "LETTER", margins: { top: 72, bottom: 72, left: 72, right: 72 } });

  const BLUE = "#032d60";
  const ACCENT = "#0176d3";
  const GRAY = "#6b7280";
  const LIGHT = "#f0f7ff";
  const W = 468; // usable width

  // Header bar
  doc.rect(72, 72, W, 56).fill(BLUE);
  doc.fillColor("#ffffff").fontSize(18).font("Helvetica-Bold")
    .text("Certificate of Electronic Signature", 90, 90, { width: W - 36 });

  // Subtitle
  doc.fillColor(ACCENT).fontSize(10).font("Helvetica")
    .text("Siebert Services — Built-in E-Sign", 72, 140);

  doc.moveDown(0.5);

  // Document name section
  doc.rect(72, 162, W, 1).fill("#e5e7eb"); // divider
  doc.fillColor(GRAY).fontSize(9).font("Helvetica-Bold")
    .text("DOCUMENT", 72, 172);
  doc.fillColor("#111827").fontSize(13).font("Helvetica-Bold")
    .text(params.documentName, 72, 186, { width: W });

  doc.rect(72, doc.y + 6, W, 1).fill("#e5e7eb");
  doc.moveDown(1.2);

  // Info rows
  const infoY = doc.y;
  const col1 = 72;
  const col2 = 290;

  function infoBlock(label: string, value: string, x: number, y: number) {
    doc.fillColor(GRAY).fontSize(8).font("Helvetica-Bold").text(label, x, y);
    doc.fillColor("#111827").fontSize(11).font("Helvetica").text(value, x, y + 13, { width: 200 });
  }

  infoBlock("SIGNED BY", params.signerName, col1, infoY);
  infoBlock("DATE SIGNED", params.signedAt.toLocaleDateString("en-US", {
    year: "numeric", month: "long", day: "numeric",
  }), col2, infoY);

  const row2Y = infoY + 46;
  infoBlock("TITLE / ROLE", params.signerTitle || "—", col1, row2Y);
  infoBlock("ENVELOPE ID", `ENV-${String(params.envelopeId).padStart(6, "0")}`, col2, row2Y);
  infoBlock("SIGNED AT (UTC)", params.signedAt.toISOString().replace("T", " ").slice(0, 19), col1, row2Y + 46);

  doc.moveDown(4.5);

  // Signature image
  const sigY = doc.y;
  doc.rect(72, sigY, W, 130).fill(LIGHT).stroke("#d1d5db");
  doc.fillColor(GRAY).fontSize(8).font("Helvetica-Bold").text("ELECTRONIC SIGNATURE", 90, sigY + 12);

  // Strip the data URL prefix and embed
  try {
    const base64Data = params.signatureImage.replace(/^data:image\/png;base64,/, "");
    const imgBuffer = Buffer.from(base64Data, "base64");
    doc.image(imgBuffer, 90, sigY + 26, { fit: [W - 36, 90] });
  } catch {
    doc.fillColor(GRAY).fontSize(10).text("[Signature image unavailable]", 90, sigY + 60);
  }

  // Signature line
  doc.moveTo(90, sigY + 122).lineTo(72 + W - 18, sigY + 122).stroke("#6b7280");

  doc.moveDown(7);

  // Legal statement
  doc.rect(72, doc.y, W, 1).fill("#e5e7eb");
  doc.moveDown(0.5);
  doc.fillColor(GRAY).fontSize(8).font("Helvetica")
    .text(
      `By signing, the party above agreed to the terms of the above-named document and authorized Siebert Services ` +
      `to proceed accordingly. This certificate was generated by the Siebert Services Built-in E-Sign system on ` +
      `${new Date().toISOString()}.`,
      72, doc.y, { width: W, align: "justify" }
    );

  // Footer
  const pageH = 792;
  doc.rect(72, pageH - 80, W, 1).fill("#e5e7eb");
  doc.fillColor(GRAY).fontSize(8).font("Helvetica")
    .text("Siebert Services LLC  ·  866-484-9180  ·  siebertrservices.com", 72, pageH - 68, { width: W, align: "center" });

  return bufferDoc(doc);
}
