import crypto from "crypto";
import PDFDocument from "pdfkit";

// ─── Built-in e-sign system ───────────────────────────────────────────────────
// No third-party provider. Tokens are generated locally; clients sign via the
// partner portal's /esign/:token page. Signed PDFs are a certificate of completion
// stored back into the documents table.

export interface EsignSigner {
  id: string;
  name: string;
  email: string;
  role?: string;
  signingOrder: number;
  /** Per-recipient signing token. Null after the signer has acted (signed/declined). */
  signingToken?: string | null;
  /** ISO timestamp set when the signer completes their action. */
  signedAt?: string | null;
}

export interface CreateEnvelopeParams {
  documentName: string;
  fileBase64: string;
  fileName: string;
  signers: EsignSigner[];
  subject?: string;
  message?: string;
}

export interface EnvelopeResult {
  providerEnvelopeId: string; // kept for DB compat — same as review_token
  reviewToken: string;
  status: string;
}

export function generateReviewToken(): string {
  return crypto.randomBytes(32).toString("hex");
}

export function isSignwellConfigured(): boolean {
  return true; // built-in — always available
}

// ─── Signature certificate PDF ────────────────────────────────────────────────

export interface SignatureCertificateParams {
  documentName: string;
  signerName: string;
  signerTitle: string | null;
  signatureImage: string; // data URL
  signedAt: Date;
  envelopeId: number;
}

export function generateSignatureCertificate(
  params: SignatureCertificateParams
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const { documentName, signerName, signerTitle, signatureImage, signedAt, envelopeId } = params;

    const doc = new PDFDocument({ margin: 60, size: "LETTER" });
    const chunks: Buffer[] = [];

    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    // Header bar
    doc.rect(0, 0, doc.page.width, 8).fill("#003087");
    doc.moveDown(0.5);

    // Title
    doc
      .fontSize(22)
      .fillColor("#003087")
      .font("Helvetica-Bold")
      .text("Certificate of Electronic Signature", { align: "center" });

    doc.moveDown(0.3);
    doc
      .fontSize(11)
      .fillColor("#555555")
      .font("Helvetica")
      .text("This certificate confirms that the document was signed electronically.", { align: "center" });

    doc.moveDown(1.5);
    doc.moveTo(60, doc.y).lineTo(doc.page.width - 60, doc.y).strokeColor("#dddddd").stroke();
    doc.moveDown(1);

    // Details table
    const labelX = 60;
    const valueX = 200;

    function row(label: string, value: string) {
      doc
        .fontSize(10)
        .fillColor("#888888")
        .font("Helvetica-Bold")
        .text(label, labelX, doc.y, { continued: false });
      doc
        .fontSize(11)
        .fillColor("#111111")
        .font("Helvetica")
        .text(value, valueX, doc.y - doc.currentLineHeight(), { lineBreak: false });
      doc.moveDown(0.9);
    }

    row("Document:", documentName);
    row("Signed by:", signerName + (signerTitle ? `, ${signerTitle}` : ""));
    row("Date signed:", signedAt.toLocaleString("en-US", { dateStyle: "long", timeStyle: "short" }));
    row("Envelope ID:", `ENV-${String(envelopeId).padStart(6, "0")}`);
    row("Method:", "Electronic Signature — Siebert Services Built-in e-Sign");

    doc.moveDown(1);
    doc.moveTo(60, doc.y).lineTo(doc.page.width - 60, doc.y).strokeColor("#dddddd").stroke();
    doc.moveDown(1.5);

    // Signature image
    doc
      .fontSize(10)
      .fillColor("#888888")
      .font("Helvetica-Bold")
      .text("Signature:", labelX);
    doc.moveDown(0.4);

    try {
      // Strip data URL prefix and embed
      const base64Data = signatureImage.replace(/^data:image\/\w+;base64,/, "");
      const imgBuffer = Buffer.from(base64Data, "base64");
      doc.image(imgBuffer, labelX, doc.y, { width: 200, height: 80 });
      doc.moveDown(5);
    } catch {
      doc.fontSize(10).fillColor("#cc0000").text("[Signature image could not be rendered]");
      doc.moveDown(1);
    }

    // Footer
    doc.moveTo(60, doc.y).lineTo(doc.page.width - 60, doc.y).strokeColor("#dddddd").stroke();
    doc.moveDown(0.8);
    doc
      .fontSize(9)
      .fillColor("#aaaaaa")
      .font("Helvetica")
      .text(
        `This certificate was generated by Siebert Services on ${new Date().toUTCString()}. ` +
          `It serves as a legally binding record of electronic consent.`,
        { align: "center" }
      );

    // Bottom bar
    doc.rect(0, doc.page.height - 8, doc.page.width, 8).fill("#003087");

    doc.end();
  });
}
